version: '2.1'        # 表示该docker-compose.yml文件使用的是Version 2 file format


services:           # Version 2 file format的固定写法，为project定义服务。
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672"
      - "56722:5672"
    labels:
      NAME: "rabbitmq"


